version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: globant
      POSTGRES_USER: globant
      POSTGRES_PASSWORD: globant
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: globant
      POSTGRES_USER: globant
      POSTGRES_PASSWORD: globant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: